spring:
  application:
    name: Test Operation Platform
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatabookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/top?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qwe123
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: top_version
    encoding: UTF-8
    validate-on-migrate: false

mybatis:
  configuration:
    cache-enabled: true
    lazy-loading-enabled: false
    aggressive-lazy-loading: true
    multiple-result-sets-enabled: true
    use-column-label: true
    auto-mapping-behavior: full
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true

